### PR TITLE
fixes broken slash slack command

### PR DESCRIPTION
**Pull request by kenliu**

### CODE REVIEW

**Comment by kenliu** [comment]
@gumatias hound this is super annoying and the code changes get lost

**Comment by gumatias** [comment]
wow those rules should not be in place at all. I'm going to disable those defaults. Feel free to disable hound for now if you want :) thanks!

**Comment by kenliu** [comment]
oh cool, we can leave in place until you fix it

On Sat, Jan 30, 2016 at 1:39 PM, Gustavo Matias <notifications@github.com>
wrote:

> wow those rules should not be in place at all. I'm going to disable those
> defaults. Feel free to disable hound for now if you want :) thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/viewthespace/pr-leaderboard/pull/6#issuecomment-177268947>
> .
>



-- 
<http://vts.com/>
Ken Liu
VP of Engineering
M (973) 637-0007
E ken@vts.com
<https://www.vts.com/testimonials>
<https://twitter.com/viewthespace>  <https://vimeo.com/viewthespace>
<https://instagram.com/viewthespace>
<https://www.linkedin.com/company/view-the-space>
<https://www.facebook.com/Viewthespace>

**Comment by gumatias** [comment]
sweet! the ability to disable the default rules in hound is actually a bug they're addressing right now. https://github.com/thoughtbot/hound/issues/1049 I'm on it.

**Comment by kenliu** [comment]
Awesome @gumatias

**Pull request closed without merging**
