### PR TITLE
Added ability to pass in previous sprint dates

### PR DESCRIPTION
**Pull request by kbaum**

### CODE REVIEW

**Comment by kbaum** [comment]
@kenliu - can you take a look when you get a chance?

**Comment by kenliu** [comment]
Sure!

On Monday, January 18, 2016, Karl Baum <notifications@github.com> wrote:

> @kenliu <https://github.com/kenliu> - can you take a look when you get a
> chance?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/viewthespace/pr-leaderboard/pull/1#issuecomment-172567674>
> .
>


-- 
Sent from my phone

**Comment by kenliu** [comment]
seemed pretty intuitive to have a method called `latest_sprint`

**Comment by kbaum** [comment]
Yes.. I guess it's intuitive but i didn't need it anymore.

**Pull request merged**
